"""Installing and removing one tool: shortcut or alias, and its Claude skill.
"""

from __future__ import annotations

import os
import shlex
import subprocess
import sys
from typing import Callable, NamedTuple, Optional

from . import host
from . import discovery
from . import state


def _skill_installed(skill_name: str) -> bool:
    """True if ~/.claude/skills/<skill_name>/SKILL.md exists."""
    if not skill_name:
        return False
    return os.path.isfile(os.path.join(state.CLAUDE_SKILLS_DIR, skill_name, "SKILL.md"))


def _skill_md_path(skill_name: str) -> str:
    return os.path.join(state.CLAUDE_SKILLS_DIR, skill_name, "SKILL.md")


def ensure_apps_dir():
    if not os.path.exists(state.APPS_DIR):
        os.makedirs(state.APPS_DIR)


def tool_shortcut_path(tool: discovery.ToolEntry) -> str:
    """Where this tool's shortcut lives: a .desktop file, or a .lnk on Windows."""
    if host.IS_WINDOWS:
        return os.path.join(state.APPS_DIR,
                            os.path.splitext(tool.desktop_file)[0] + ".lnk")
    return os.path.join(state.APPS_DIR, tool.desktop_file)


def _load_shims() -> dict:
    """Windows equivalent of _load_aliases: the installed shims, read back as
    alias name -> command line, so the callers below need no Windows branch."""
    shim_dir = state.IDENTITY.shim_path
    commands = {}
    try:
        names = os.listdir(shim_dir)
    except OSError:
        return commands
    for name in names:
        if not name.endswith(".cmd"):
            continue
        try:
            with open(os.path.join(shim_dir, name), "r") as fh:
                lines = [ln.strip() for ln in fh if ln.strip()]
        except OSError:
            continue
        for line in lines:
            if line.lower().startswith("@echo"):
                continue
            commands[name[:-4]] = line.removesuffix(" %*").strip()
            break
    return commands


def _load_aliases() -> dict:
    """Load existing aliases from file. Returns dict of alias_name -> command."""
    if host.IS_WINDOWS:
        return _load_shims()
    aliases = {}
    if os.path.exists(state.ALIASES_FILE):
        with open(state.ALIASES_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if line.startswith("alias ") and "=" in line:
                    parts = line[6:].split("=", 1)
                    if len(parts) == 2:
                        name = parts[0].strip()
                        cmd = parts[1].strip()
                        # Only strip the OUTER wrapping quotes — never a blanket
                        # .strip("'\""), which would eat a balanced inner quote
                        # (e.g. the closing `"` of `python "/path/main.py"`) and
                        # corrupt the alias on the next save.
                        if (cmd.startswith("'") and cmd.endswith("'")) or \
                           (cmd.startswith('"') and cmd.endswith('"')):
                            cmd = cmd[1:-1]
                        aliases[name] = cmd
    return aliases


def _find_alias_for_script(script_path: str) -> str | None:
    """Find which alias (if any) points to a given script path.

    Returns the alias name if found, None otherwise.
    """
    aliases = _load_aliases()
    for alias_name, cmd in aliases.items():
        # Commands look like: /usr/bin/python3 "/path/to/script.py"
        if script_path in cmd:
            return alias_name
    return None


def _save_aliases(aliases: dict) -> None:
    """Save aliases to file.

    On Windows there is no alias file: the shims are the aliases, so this
    deletes the shims of every name that is no longer in the dict. The
    remaining shims are written by each tool's own --install.
    """
    if host.IS_WINDOWS:
        shim_dir = state.IDENTITY.shim_path
        for name in _load_shims():
            if name not in aliases:
                host.remove_shims(shim_dir, name)
        return
    with open(state.ALIASES_FILE, "w") as f:
        f.write("# Auto-generated by tools installer - do not edit manually\n")
        f.write("# Source this file in your .bashrc/.zshrc:\n")
        f.write(f"#   [ -f {state.ALIASES_FILE} ] && source {state.ALIASES_FILE}\n\n")
        for name, cmd in sorted(aliases.items()):
            # shlex.quote so an inner quote (e.g. the `"` around the script
            # path) survives the round-trip instead of being written into a
            # raw '{cmd}' wrapper that leaves the inner quote unbalanced.
            f.write(f"alias {name}={shlex.quote(cmd)}\n")


def is_installed(tool: discovery.ToolEntry) -> bool:
    """Check if a tool is installed based on its tags."""
    has_icon = "Icon" in tool.tags
    if has_icon:
        # Check for the .desktop file (a .lnk on Windows)
        return os.path.exists(tool_shortcut_path(tool))
    else:
        # Check if ANY alias points to this script (not just the expected one)
        return _find_alias_for_script(tool.script_path) is not None


def needs_update(tool: discovery.ToolEntry) -> bool:
    """Check if an installed tool has outdated metadata (e.g., renamed alias).

    Returns True if the tool is installed but its configuration differs from
    what's advertised (different alias name, different args, etc.)
    """
    has_icon = "Icon" in tool.tags
    if has_icon:
        if host.IS_WINDOWS:
            return False  # a .lnk is binary; nothing to compare the path against
        # For desktop files, check if the Exec path matches the current script path
        desktop_path = os.path.join(state.APPS_DIR, tool.desktop_file)
        if not os.path.exists(desktop_path):
            return False
        # Parse the desktop file to check if Exec path matches
        try:
            with open(desktop_path, "r") as f:
                for line in f:
                    if line.startswith("Exec="):
                        # Exec line format: Exec=/path/to/python "/path/to/script.py" --args
                        # Check if our script_path is in the Exec line
                        if tool.script_path not in line:
                            return True  # Script path changed, needs update
                        break
        except (IOError, OSError):
            pass
        return False
    else:
        # For aliases, this entry is current iff *its own* alias points at the
        # script. Several entries can legitimately share one script (e.g. the
        # `scrape` dispatcher + `scrape-yt` plugin both alias scrape/main.py), so
        # comparing against the first-found alias would false-flag every-but-one
        # of them forever. Only when NONE of this script's aliases is this entry's
        # alias is it a genuine rename that needs updating.
        aliases_for_script = [name for name, cmd in _load_aliases().items()
                              if tool.script_path in cmd]
        if not aliases_for_script:
            return False  # Not installed
        return tool.alias not in aliases_for_script  # installed under a different name → rename


def install_tool(tool: discovery.ToolEntry, skip_deps: bool = False) -> tuple[bool, str]:
    """Invokes the tool's own --install argument. Returns (success, output).

    When skip_deps is True, sets TOOLS_INSTALLER_SKIP_DEPS=1 in the child
    environment so the shared ToolInstaller writes the .desktop/alias without
    running 'pip install'. This keeps a shortcut refresh local and network-free.
    """
    try:
        cmd = [sys.executable, tool.script_path, "--install"] + tool.args
        env = os.environ.copy()
        # The tool writes its own .desktop and alias via ToolInstaller, so it
        # needs to know which installer asked — otherwise a third-party org's
        # tools get branded with the first-party marker and land in the
        # first-party alias file.
        env.update(state.IDENTITY.env())
        if skip_deps:
            env["TOOLS_INSTALLER_SKIP_DEPS"] = "1"
        result = subprocess.run(cmd, cwd=os.path.dirname(tool.script_path),
                                capture_output=True, encoding="utf-8", errors="replace",
                                env=host.child_env(env))
        output = (result.stdout + result.stderr).strip()
        if result.returncode == 0:
            return True, output
        else:
            return False, output or f"Exit code: {result.returncode}"
    except Exception as e:
        return False, str(e)


def remove_tool(tool: discovery.ToolEntry) -> tuple[bool, str]:
    """Invokes the tool's own --remove argument. Returns (success, output)."""
    try:
        cmd = [sys.executable, tool.script_path, "--remove"] + tool.args
        env = os.environ.copy()
        env.update(state.IDENTITY.env())   # remove the alias from OUR alias file
        result = subprocess.run(cmd, cwd=os.path.dirname(tool.script_path),
                                capture_output=True, encoding="utf-8", errors="replace",
                                env=host.child_env(env))
        output = (result.stdout + result.stderr).strip()
        if result.returncode == 0:
            return True, output
        else:
            return False, output or f"Exit code: {result.returncode}"
    except Exception as e:
        return False, str(e)


def install_skill_for_tool(tool: discovery.ToolEntry) -> tuple[bool, str]:
    """Invokes the tool's --install-skill argument. Returns (success, output).

    Used by the installer GUI when the per-row 'Skill' checkbox is toggled
    on for a tool that advertises a skill_name. Idempotent: tools should
    detect an up-to-date SKILL.md and no-op.
    """
    try:
        cmd = [sys.executable, tool.script_path, "--install-skill"] + tool.args
        result = subprocess.run(cmd, cwd=os.path.dirname(tool.script_path),
                                capture_output=True, encoding="utf-8", errors="replace",
                                env=host.child_env())
        output = (result.stdout + result.stderr).strip()
        if result.returncode == 0:
            return True, output
        return False, output or f"Exit code: {result.returncode}"
    except Exception as e:
        return False, str(e)


def uninstall_skill_for_tool(tool: discovery.ToolEntry) -> tuple[bool, str]:
    """Invokes the tool's --uninstall-skill argument. Returns (success, output)."""
    try:
        cmd = [sys.executable, tool.script_path, "--uninstall-skill"] + tool.args
        result = subprocess.run(cmd, cwd=os.path.dirname(tool.script_path),
                                capture_output=True, encoding="utf-8", errors="replace",
                                env=host.child_env())
        output = (result.stdout + result.stderr).strip()
        if result.returncode == 0:
            return True, output
        return False, output or f"Exit code: {result.returncode}"
    except Exception as e:
        return False, str(e)


class InstallHooks(NamedTuple):
    """Replacements for the four actions the engine takes on one tool.

    Pass one to ``run(hooks=...)`` (or ``sources.run_installer``). A field left
    ``None`` keeps the kit's own function. Each hook takes the ToolEntry, plus
    ``skip_deps`` for ``install_tool``, and returns ``(ok, output)``.

    Before 1.0, wrappers assigned ``gui_installer.install_tool = ...``
    directly. That still works in 1.x, but this is the supported way.
    """
    install_tool: Optional[Callable[..., tuple]] = None
    remove_tool: Optional[Callable[[discovery.ToolEntry], tuple]] = None
    install_skill: Optional[Callable[[discovery.ToolEntry], tuple]] = None
    uninstall_skill: Optional[Callable[[discovery.ToolEntry], tuple]] = None


def _apply_hooks(hooks: InstallHooks) -> None:
    """Rebind the module functions every screen looks up at call time."""
    global install_tool, remove_tool, install_skill_for_tool, uninstall_skill_for_tool
    if hooks.install_tool is not None:
        install_tool = hooks.install_tool
    if hooks.remove_tool is not None:
        remove_tool = hooks.remove_tool
    if hooks.install_skill is not None:
        install_skill_for_tool = hooks.install_skill
    if hooks.uninstall_skill is not None:
        uninstall_skill_for_tool = hooks.uninstall_skill


def refresh_desktop_database():
    if host.IS_WINDOWS:
        return
    for cmd in ["update-desktop-database", "kbuildsycoca5"]:
        try:
            subprocess.run([cmd, state.APPS_DIR if cmd == "update-desktop-database" else ""],
                           stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        except:
            pass
